package com.stripedlens.calcloner.util

import android.database.ContentObserver
import android.net.Uri
import android.os.Handler
import android.os.Looper
import com.stripedlens.calcloner.CalendarSyncEngine
import kotlinx.coroutines.*

/**
 * Lifecycle-aware ContentObserver that listens to local calendar database mutations
 * while CalCloner is actively open in the foreground.
 *
 * Implements an 800ms coroutine debounce and echo suppression to avoid triggering
 * duplicate sync cycles from CalCloner's own writes.
 */
class CalendarContentObserver(
    private val scope: CoroutineScope,
    val debounceDelayMs: Long = 800L,
    handler: Handler? = try { Handler(Looper.getMainLooper()) } catch (_: Exception) { null },
    private val onChangeDebounced: () -> Unit
) : ContentObserver(handler) {

    var debounceJob: Job? = null
        private set

    override fun onChange(selfChange: Boolean, uri: Uri?) {
        // Echo Suppression: Ignore writes generated by CalCloner's writer
        val timeSinceLastSelfWrite = System.currentTimeMillis() - CalendarSyncEngine.lastSelfWriteTimestamp
        if (timeSinceLastSelfWrite in 0..10_000L) {
            return
        }

        // Debounce to coalesce rapid multi-row batch inserts / edits
        debounceJob?.cancel()
        debounceJob = scope.launch {
            delay(debounceDelayMs)
            onChangeDebounced()
        }
    }
}
